// <auto-generated />
using System;
using InternalBaseWpf.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternalBaseWpf.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614203729_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InternalBaseWpf.Models.Activist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("bit");

                    b.Property<string>("CitizenshipCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImportStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAts")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPartySupporter")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPresidentSupporter")
                        .HasColumnType("bit");

                    b.Property<bool>("IsResponsible")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVdlSupporter")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVverh")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalBranch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loyalty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MainCellId")
                        .HasColumnType("int");

                    b.Property<bool>("MarkedForDeletionByResponsible")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartyStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryBranch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Readiness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionalReadiness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int");

                    b.Property<string>("TargetAudience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UikNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workplace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MainCellId");

                    b.HasIndex("ResponsibleUserId");

                    b.ToTable("Activists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "г. Пермь, ул. Ленина, д. 1",
                            BirthDate = new DateTime(1980, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CanEdit = false,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Иван",
                            Gender = "Мужской",
                            IsAts = false,
                            IsConfirmed = true,
                            IsPartySupporter = false,
                            IsPresidentSupporter = false,
                            IsResponsible = false,
                            IsVdlSupporter = false,
                            IsVverh = false,
                            LastName = "Иванов",
                            LocalBranch = "МО Куединского муниципального округа",
                            MarkedForDeletionByResponsible = false,
                            Patronymic = "Иванович",
                            Phone = "(912) 345-67-89",
                            UikNumber = "1822"
                        },
                        new
                        {
                            Id = 2,
                            Address = "г. Пермь, ул. Гагарина, д. 5",
                            BirthDate = new DateTime(1992, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CanEdit = false,
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Мария",
                            Gender = "Женский",
                            IsAts = false,
                            IsConfirmed = true,
                            IsPartySupporter = false,
                            IsPresidentSupporter = false,
                            IsResponsible = false,
                            IsVdlSupporter = false,
                            IsVverh = false,
                            LastName = "Петрова",
                            LocalBranch = "МО Куединского муниципального округа",
                            MainCellId = 2,
                            MarkedForDeletionByResponsible = false,
                            Patronymic = "Сергеевна",
                            Phone = "(922) 456-78-90",
                            UikNumber = "1823"
                        },
                        new
                        {
                            Id = 3,
                            Address = "г. Пермь, ул. Ленина, д. 2",
                            BirthDate = new DateTime(1980, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CanEdit = false,
                            CreatedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Иван",
                            Gender = "Мужской",
                            IsAts = false,
                            IsConfirmed = true,
                            IsPartySupporter = false,
                            IsPresidentSupporter = false,
                            IsResponsible = false,
                            IsVdlSupporter = false,
                            IsVverh = false,
                            LastName = "Иванов",
                            LocalBranch = "МО Куединского муниципального округа",
                            MarkedForDeletionByResponsible = false,
                            Patronymic = "Иванович",
                            Phone = "(912) 345-67-99",
                            UikNumber = "1822"
                        });
                });

            modelBuilder.Entity("InternalBaseWpf.Models.ActivistCell", b =>
                {
                    b.Property<int>("ActivistId")
                        .HasColumnType("int");

                    b.Property<int>("CellId")
                        .HasColumnType("int");

                    b.HasKey("ActivistId", "CellId");

                    b.HasIndex("CellId");

                    b.ToTable("ActivistCells");
                });

            modelBuilder.Entity("InternalBaseWpf.Models.Cell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cells");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 15, 1, 37, 29, 470, DateTimeKind.Local).AddTicks(2908),
                            IsActive = true,
                            Name = "МО Куединского р-на"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 15, 1, 37, 29, 470, DateTimeKind.Local).AddTicks(2911),
                            IsActive = true,
                            Name = "Куединское РДК"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 15, 1, 37, 29, 470, DateTimeKind.Local).AddTicks(2912),
                            IsActive = true,
                            Name = "Сайт Конституция МО Куединского муниципального округа"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 15, 1, 37, 29, 470, DateTimeKind.Local).AddTicks(2913),
                            IsActive = true,
                            Name = "Сторонники МО Куединского муниципального округа"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 15, 1, 37, 29, 470, DateTimeKind.Local).AddTicks(2914),
                            IsActive = true,
                            Name = "Молодёжный совет Куединского МО"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 15, 1, 37, 29, 470, DateTimeKind.Local).AddTicks(2915),
                            IsActive = true,
                            Name = "Совет ветеранов Куединского МО"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 15, 1, 37, 29, 470, DateTimeKind.Local).AddTicks(2916),
                            IsActive = true,
                            Name = "ТИК Куединского МО"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 15, 1, 37, 29, 470, DateTimeKind.Local).AddTicks(2917),
                            IsActive = true,
                            Name = "Общественная палата Куединского МО"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 6, 15, 1, 37, 29, 470, DateTimeKind.Local).AddTicks(2918),
                            IsActive = true,
                            Name = "Центральная библиотека Куединского МО"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 6, 15, 1, 37, 29, 470, DateTimeKind.Local).AddTicks(2919),
                            IsActive = true,
                            Name = "Краеведческий музей Куединского МО"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 6, 15, 1, 37, 29, 470, DateTimeKind.Local).AddTicks(2920),
                            IsActive = true,
                            Name = "Спортивный клуб Куединского МО"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 6, 15, 1, 37, 29, 470, DateTimeKind.Local).AddTicks(2921),
                            IsActive = true,
                            Name = "Волонтёрский центр Куединского МО"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 6, 15, 1, 37, 29, 470, DateTimeKind.Local).AddTicks(2922),
                            IsActive = true,
                            Name = "Куединский районный Дом культуры"
                        });
                });

            modelBuilder.Entity("InternalBaseWpf.Models.Touch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CellId")
                        .HasColumnType("int");

                    b.Property<int?>("Coverage")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasPhoto")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPublication")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCuratorApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRikPlaced")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShopPlaced")
                        .HasColumnType("bit");

                    b.Property<string>("MediaLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("int");

                    b.Property<string>("SocialLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CellId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("TypeId");

                    b.ToTable("Touches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CellId = 2,
                            Coverage = 40,
                            CreatedAt = new DateTime(2026, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasPhoto = false,
                            HasPublication = false,
                            IsActive = true,
                            IsCuratorApproved = false,
                            IsRikPlaced = false,
                            IsShopPlaced = false,
                            Name = "День России",
                            OperatorId = 2,
                            StartDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CellId = 2,
                            Coverage = 60,
                            CreatedAt = new DateTime(2026, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasPhoto = false,
                            HasPublication = false,
                            IsActive = true,
                            IsCuratorApproved = false,
                            IsRikPlaced = false,
                            IsShopPlaced = false,
                            Name = "День молодёжи",
                            OperatorId = 2,
                            StartDate = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 1
                        });
                });

            modelBuilder.Entity("InternalBaseWpf.Models.TouchType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TouchTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Оффлайн мероприятие"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Онлайн мероприятие"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Иное"
                        });
                });

            modelBuilder.Entity("InternalBaseWpf.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Администратор",
                            IsActive = true,
                            IsAdmin = true,
                            Login = "admin",
                            PasswordHash = "ktOd8bsFgodSF5PAcB+O2X3AI4kwnN7sDJHQ5a0SIzA=",
                            Salt = "Mo7vjCmXyZj+O23K8eMD3g=="
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ирина Рогова",
                            IsActive = true,
                            IsAdmin = false,
                            Login = "rogova",
                            PasswordHash = "ktOd8bsFgodSF5PAcB+O2X3AI4kwnN7sDJHQ5a0SIzA=",
                            Salt = "Mo7vjCmXyZj+O23K8eMD3g=="
                        });
                });

            modelBuilder.Entity("InternalBaseWpf.Models.Activist", b =>
                {
                    b.HasOne("InternalBaseWpf.Models.Cell", "MainCell")
                        .WithMany("MainActivists")
                        .HasForeignKey("MainCellId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InternalBaseWpf.Models.User", "ResponsibleUser")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MainCell");

                    b.Navigation("ResponsibleUser");
                });

            modelBuilder.Entity("InternalBaseWpf.Models.ActivistCell", b =>
                {
                    b.HasOne("InternalBaseWpf.Models.Activist", "Activist")
                        .WithMany("ActivistCells")
                        .HasForeignKey("ActivistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternalBaseWpf.Models.Cell", "Cell")
                        .WithMany("ActivistCells")
                        .HasForeignKey("CellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activist");

                    b.Navigation("Cell");
                });

            modelBuilder.Entity("InternalBaseWpf.Models.Touch", b =>
                {
                    b.HasOne("InternalBaseWpf.Models.Cell", "Cell")
                        .WithMany("Touches")
                        .HasForeignKey("CellId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InternalBaseWpf.Models.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InternalBaseWpf.Models.TouchType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cell");

                    b.Navigation("Operator");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("InternalBaseWpf.Models.Activist", b =>
                {
                    b.Navigation("ActivistCells");
                });

            modelBuilder.Entity("InternalBaseWpf.Models.Cell", b =>
                {
                    b.Navigation("ActivistCells");

                    b.Navigation("MainActivists");

                    b.Navigation("Touches");
                });
#pragma warning restore 612, 618
        }
    }
}
