// <auto-generated />
using System;
using InternalBaseWpf.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternalBaseWpf.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614201218_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InternalBaseWpf.Models.Activist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("bit");

                    b.Property<string>("CitizenshipCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImportStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAts")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPartySupporter")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPresidentSupporter")
                        .HasColumnType("bit");

                    b.Property<bool>("IsResponsible")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVdlSupporter")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVverh")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalBranch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loyalty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MainCellId")
                        .HasColumnType("int");

                    b.Property<bool>("MarkedForDeletionByResponsible")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartyStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryBranch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Readiness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionalReadiness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int");

                    b.Property<string>("TargetAudience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UikNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workplace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MainCellId");

                    b.HasIndex("ResponsibleUserId");

                    b.ToTable("Activists");
                });

            modelBuilder.Entity("InternalBaseWpf.Models.ActivistCell", b =>
                {
                    b.Property<int>("ActivistId")
                        .HasColumnType("int");

                    b.Property<int>("CellId")
                        .HasColumnType("int");

                    b.HasKey("ActivistId", "CellId");

                    b.HasIndex("CellId");

                    b.ToTable("ActivistCells");
                });

            modelBuilder.Entity("InternalBaseWpf.Models.Cell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cells");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 15, 1, 12, 17, 760, DateTimeKind.Local).AddTicks(826),
                            IsActive = true,
                            Name = "МО Куединского р-на"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 15, 1, 12, 17, 760, DateTimeKind.Local).AddTicks(830),
                            IsActive = true,
                            Name = "Куединское РДК"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 15, 1, 12, 17, 760, DateTimeKind.Local).AddTicks(831),
                            IsActive = true,
                            Name = "Сайт Конституция МО Куединского муниципального округа"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 15, 1, 12, 17, 760, DateTimeKind.Local).AddTicks(832),
                            IsActive = true,
                            Name = "Сторонники МО Куединского муниципального округа"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 15, 1, 12, 17, 760, DateTimeKind.Local).AddTicks(833),
                            IsActive = true,
                            Name = "Молодёжный совет Куединского МО"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 15, 1, 12, 17, 760, DateTimeKind.Local).AddTicks(834),
                            IsActive = true,
                            Name = "Совет ветеранов Куединского МО"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 15, 1, 12, 17, 760, DateTimeKind.Local).AddTicks(835),
                            IsActive = true,
                            Name = "ТИК Куединского МО"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 15, 1, 12, 17, 760, DateTimeKind.Local).AddTicks(836),
                            IsActive = true,
                            Name = "Общественная палата Куединского МО"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 6, 15, 1, 12, 17, 760, DateTimeKind.Local).AddTicks(837),
                            IsActive = true,
                            Name = "Центральная библиотека Куединского МО"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 6, 15, 1, 12, 17, 760, DateTimeKind.Local).AddTicks(838),
                            IsActive = true,
                            Name = "Краеведческий музей Куединского МО"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 6, 15, 1, 12, 17, 760, DateTimeKind.Local).AddTicks(839),
                            IsActive = true,
                            Name = "Спортивный клуб Куединского МО"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 6, 15, 1, 12, 17, 760, DateTimeKind.Local).AddTicks(840),
                            IsActive = true,
                            Name = "Волонтёрский центр Куединского МО"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 6, 15, 1, 12, 17, 760, DateTimeKind.Local).AddTicks(841),
                            IsActive = true,
                            Name = "Куединский районный Дом культуры"
                        });
                });

            modelBuilder.Entity("InternalBaseWpf.Models.Touch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CellId")
                        .HasColumnType("int");

                    b.Property<int?>("Coverage")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasPhoto")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPublication")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCuratorApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRikPlaced")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShopPlaced")
                        .HasColumnType("bit");

                    b.Property<string>("MediaLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("int");

                    b.Property<string>("SocialLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CellId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("TypeId");

                    b.ToTable("Touches");
                });

            modelBuilder.Entity("InternalBaseWpf.Models.TouchType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TouchTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Оффлайн мероприятие"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Онлайн мероприятие"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Иное"
                        });
                });

            modelBuilder.Entity("InternalBaseWpf.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Администратор",
                            IsActive = true,
                            IsAdmin = true,
                            Login = "admin",
                            PasswordHash = "Ds0HkiyNb9LeNStqweOQ/IGzP2c4jJ5TBMIOAnE3PjQ=",
                            Salt = "hU4MJ0AqvUKNBV56RJA/WA=="
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ирина Рогова",
                            IsActive = true,
                            IsAdmin = false,
                            Login = "rogova",
                            PasswordHash = "Ds0HkiyNb9LeNStqweOQ/IGzP2c4jJ5TBMIOAnE3PjQ=",
                            Salt = "hU4MJ0AqvUKNBV56RJA/WA=="
                        });
                });

            modelBuilder.Entity("InternalBaseWpf.Models.Activist", b =>
                {
                    b.HasOne("InternalBaseWpf.Models.Cell", "MainCell")
                        .WithMany("MainActivists")
                        .HasForeignKey("MainCellId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InternalBaseWpf.Models.User", "ResponsibleUser")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MainCell");

                    b.Navigation("ResponsibleUser");
                });

            modelBuilder.Entity("InternalBaseWpf.Models.ActivistCell", b =>
                {
                    b.HasOne("InternalBaseWpf.Models.Activist", "Activist")
                        .WithMany("ActivistCells")
                        .HasForeignKey("ActivistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternalBaseWpf.Models.Cell", "Cell")
                        .WithMany("ActivistCells")
                        .HasForeignKey("CellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activist");

                    b.Navigation("Cell");
                });

            modelBuilder.Entity("InternalBaseWpf.Models.Touch", b =>
                {
                    b.HasOne("InternalBaseWpf.Models.Cell", "Cell")
                        .WithMany("Touches")
                        .HasForeignKey("CellId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InternalBaseWpf.Models.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InternalBaseWpf.Models.TouchType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cell");

                    b.Navigation("Operator");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("InternalBaseWpf.Models.Activist", b =>
                {
                    b.Navigation("ActivistCells");
                });

            modelBuilder.Entity("InternalBaseWpf.Models.Cell", b =>
                {
                    b.Navigation("ActivistCells");

                    b.Navigation("MainActivists");

                    b.Navigation("Touches");
                });
#pragma warning restore 612, 618
        }
    }
}
